DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS ITEMS CASCADE;
DROP TABLE IF EXISTS BOOKINGS CASCADE;
DROP TABLE IF EXISTS REQUESTS CASCADE;
DROP TABLE IF EXISTS COMMENTS CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(50)                             NOT NULL,
    email           VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(50)                             NOT NULL,
    description     VARCHAR(512)                            NOT NULL,
    available       BOOLEAN                                 NOT NULL,
    owner_id        BIGINT                                  NOT NULL,
    request_id      BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_owner_id FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    item_id         BIGINT                                  NOT NULL,
    booker_id       BIGINT                                  NOT NULL,
    status          VARCHAR(8),
    CONSTRAINT pk_bookings PRIMARY KEY (id),
    CONSTRAINT fk_booker_id FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description     VARCHAR(512)                            NOT NULL,
    requestor_id    BIGINT,
    created         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_requests PRIMARY KEY (id),
    CONSTRAINT fk_requestor_id FOREIGN KEY (requestor_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text            VARCHAR(512)                            NOT NULL,
    item_id         BIGINT                                  NOT NULL,
    author_id       BIGINT                                  NOT NULL,
    created         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_item_id FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_id FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);